FROM node:18 as loginportal
WORKDIR /login
COPY package*.json .
RUN yarn install --frozen-lockfile
COPY . .
RUN yarn build

#FROM swecon18ab/nginx:latest
FROM swecon18ab/nginx:latest
# Set working directory to nginx asset directory
WORKDIR /usr/share/nginx/html

# Copy the build output from the build container #Adjusted path to buid
COPY --from=loginportal /login/build ./ 


EXPOSE 5510
# Containers run nginx with global directives and daemon off
ENTRYPOINT ["nginx", "-g", "daemon off;"]
